# Generated by Django 3.0.5 on 2020-05-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='table',
            new_name='title',
        ),
    ]
